# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "developer"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/site.yml"
    ansible.groups = {
      "developer" => ["developer"]
    }
  end
end
