---
- name: Add X environment
  apt: name={{ item.pkg }} state=present
  become: yes
  with_items:
    - { pkg: "ubuntu-desktop" }

# https://download.jetbrains.com/cpp/CLion-2016.2.2.tar.gz
# b1595466ff890067dda8e0176dd815a825fb86fc2b6ef90610294ec61c1d5819 *CLion-2016.2.2.tar.gz
- name: Download clion
  get_url:
    url: https://download.jetbrains.com/cpp/CLion-2016.2.2.tar.gz
    dest: /var/tmp/CLion-2016.2.2.tar.gz
    checksum: sha256:b1595466ff890067dda8e0176dd815a825fb86fc2b6ef90610294ec61c1d5819 

- name: Unpack CLion
  unarchive:
    src: /var/tmp/CLion-2016.2.2.tar.gz
    dest: /home/ubuntu

